```{r, echo = FALSE, message = FALSE}

source(here::here("scripts/setup.R"))
```

::: h1-flex-container
# Introduction {.title-with-lines}
:::

## Overview and Motivation

Road accidents continue to be one of the leading causes of death and hospitalizations around the world. Many factors such as weather, driver behavior and demographics contribute to a substantial number of deaths worldwide each year (1.3M on average based on research conducted by the WHO). These road accidents remain complicated and provide a great base of information in which we can put our data science toolkit to work to discover and reveal hidden information on patterns and insights into what influences road safety.

The motivation behind our choice of project (UK Road Accident Analysis) is deeply rooted in personal experiences of the members of our group. Witnessing the life-altering consequences of road accidents firsthand has ignited a passion for understanding the factors that contribute to such accidents on the road. This emotional connection, combined with the fact that all our team members having to complete "Cours 2 phases" classes mandatory for our licenses, which explain the impacts of road accidents, has created a deep curiosity for the subject.

Beyond the emotional and curiosity realm, our team recognizes that our selected data sets offer a wealth of tangible data, enabling us to explore various data science domains. This project will facilitate the enhancement of our descriptive, regression, and spatial-temporal analytically skills, empowering us to discern patterns and relationships within the data.

## Objectives:

Our project is focused on understanding and predicting the patterns of road accidents. We are concentrating on three key aspects: utilizing spatial analysis to pinpoint areas prone to accidents, examining temporal patterns to identify peak accident times, and exploring the influence of demographics and vehicle types on these occurrences. Following the identification of key factors leading to road accidents, our next step involves developing a sophisticated predictive model. This model aims to accurately determine the severity of accidents, thereby refining our expertise in data analysis and statistical modeling. Our comprehensive approach is designed to offer deeper insights into road safety, ultimately contributing to more effective accident prevention strategies.

### Research questions

[***a) Can we identify locations (geographical (coordinate based) and spatial (urban vs rural, highway vs one way road) that are more prone to accidents?***]{.underline}

[***b) What temporal trends (time of day/month/week, seasonality) can we identify in road accidents in the UK ? Can we identify the most dangerous times to be on the road?***]{.underline}

[***c) What are the most prevalent demographics (age, gender) and vehicles characteristics (engine size, electric vs petrol, etc.) of road accidents?***]{.underline}

[***d) Can we predict the severity of an accident using significant variables in our dataset and validate its accuracy?***]{.underline}

## Related Work
